name:                haskell-crypto
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/githubuser/haskell-crypto#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - cryptohash
  - bytestring
  - byteable
  - directory
  # - base-compat >= 0.8
  # - deepseq
  # - filepath
  # - Glob
  # - text
  # - containers
  # - unordered-containers
  # - yaml
  # - aeson >= 0.11

library:
  source-dirs:      src
  exposed-modules:  Crypto

# executables:
#   haskell-crypto:
#     source-dirs:      src
#     main:             Main.hs
